### ISSUE TITLE
Rotate Array Program

### ISSUE THREAD

**Issue by jatinagg2** [jatinagg2/OOPS-Programs-Hacktoberfest-2021#2]
Code the given problem in any programming language. Your code should be appropriate and avoid extra spaces.

Statement:
You have been given a random integer array/list(ARR) of size N. Write a function that rotates the given array/list by D elements(towards the left).

Input format:
The first line contains an Integer 't' which denotes the number of test cases or queries to be run. Then the test cases follow.
First line of each test case or query contains an integer 'N' representing the size of the array/list.
Second line contains 'N' single space separated integers representing the elements in the array/list.
Third line contains the value of 'D' by which the array/list needs to be rotated.

Output Format:
For each test case, print the rotated array/list in a row separated by a single space.
Output for every test case will be printed in a separate line.

Constraints:
1 <= t <= 10^4
0 <= N <= 10^6
0 <= D <= N
Time Limit: 1 sec

Sample Input:
1
7
1 2 3 4 5 6 7
2

Sample Output:
3 4 5 6 7 1 2

**Comment by Harsh-COE** [comment]
please assign

**Comment by atingarg1406** [comment]
I can solve the given problem using Python programming language. Please assign me for that.

**Comment by jatinagg2** [comment]
Go ahead @Harsh-COE @atingarg1406
