### ISSUE TITLE
Triplet sum program

### ISSUE THREAD

**Issue by jatinagg2** [jatinagg2/OOPS-Programs-Hacktoberfest-2021#5]
Code the given problem in any of the programming language.

Statement:
You have been given a random integer array/list(ARR) and a number X. Find and return the triplet(s) in the array/list which sum to X.

Input format:
The first line contains an Integer 't' which denotes the number of test cases or queries to be run. Then the test cases follow.
First line of each test case or query contains an integer 'N' representing the size of the first array/list.
Second line contains 'N' single space separated integers representing the elements in the array/list.
Third line contains an integer 'X'.

Output format:
For each test case, print the total number of triplets present in the array/list.
Output for every test case will be printed in a separate line.

Constraints:
1 <= t <= 10^2
0 <= N <= 10^3
0 <= X <= 10^9
Time Limit: 1 sec

Sample Input:
1
7
1 2 3 4 5 6 7 
12

Sample Output:
5

**Comment by atingarg1406** [comment]
I can solve this using Python. Please assign it for that.
